title: PyTennessee 2018
email: organizers@pytennessee.org

baseurl: ""
url: "https://www.pytennessee.org"
twitter_username: pytennessee

timezone: America/Chicago

permalink: pretty

exclude:
    - Gemfile
    - Gemfile.lock
    - pytn-2019.iml
    - README.md
